version: '3.3'
services:
  web:
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    image: droid-downloader-backend
    ports:
     - "3000:3000"
    secrets:
      - postgres-password

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  postgres:
    environment:
      - POSTGRES_USER=ddb
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    image: mdillon/postgis
    ports:
      - "5432:5432"
    restart: always
    secrets:
        - postgres-password
    volumes:
      - pgdata:/var/lib/postgresql/data

secrets:
  postgres-password:
    file: ./secrets/postgres-password

volumes:
  pgdata: {}